app/routes/auth_routes.py
import os
from typing import Optional
from flask import (
    Response,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    Blueprint,
    url_for,
)
from marshmallow import Schema, ValidationError, fields, post_load, pre_load, validate
from marshmallow.validate import Length

from app.auth import (
    auth_required,
    get_token_and_user_id_from_cookies,
    redirect_if_logged_in,
)
from app.models.models import Credentials, Users
from app.extensions import redis_cache
from app.routes import (
    create_and_store_access_token_in_cache,
    flatten_validation_errors,
)
from app.services.password_recovery_service import PasswordRecoveryService
from app.utils.utils import create_salt, hash_password


auth_blueprint = Blueprint("auth_blueprint", __name__)


MIN_LOGIN_LEN = 3
MAX_LOGIN_LEN = 20
MIN_PASS_LEN = 7
MAX_PASS_LEN = 20


class LoginUserSchema(Schema):
    login = fields.String(
        required=True,
        validate=Length(min=MIN_LOGIN_LEN, max=MAX_LOGIN_LEN),
    )
    password = fields.String(
        required=True,
        validate=Length(min=MIN_PASS_LEN, max=MAX_PASS_LEN),
    )

    @post_load
    def cleanup(self, data, **kwargs):
        data["login"] = data.get("login").lower().strip()

        return data


def validate_email(value: Optional[str]):
    if value in (None, ""):
        return True
    try:
        validate.Email(error="Invalid email address")(value)
    except ValidationError:
        raise ValidationError("Invalid email address")


class RegisterUserSchema(Schema):
    login = fields.String(
        required=True,
        validate=Length(min=MIN_LOGIN_LEN, max=MAX_LOGIN_LEN),
    )
    password = fields.String(
        required=True,
        validate=Length(min=MIN_PASS_LEN, max=MAX_PASS_LEN),
    )
    password_repeat = fields.String(
        required=True,
        validate=Length(min=MIN_PASS_LEN, max=MAX_PASS_LEN),
    )
    email = fields.String(
        required=False,
        allow_none=True,
        validate=validate_email,
    )
    nick = fields.String(
        required=False,
        allow_none=True,
        validate=Length(min=3, max=20),
    )

    @pre_load
    def normalize_empty_string(self, data, **kwargs):
        data = dict(data)
        if data["nick"] == "":
            data["nick"] = None
        return data


@auth_blueprint.route("/login", methods=["GET"])
@redirect_if_logged_in
def render_login():
    flash_msg = []

    user_agent = request.user_agent.string
    if "Mobile" in user_agent or "Android" in user_agent or "iPhone" in user_agent:
        flash_msg.append(
            "Please note that for the best experience, a desktop browser is preferred."
        )

    if os.getenv("SHOW_READONLY_MSG") == "true":
        msg: str = (
            "If you would like to see a readonly version with demo data without creating an "
            f"account, please use login: <i>readonly</i>, password: <i>{os.getenv('R_O_PASS')}</i> as credentials"
        )

        flash_msg.append(msg)

    if flash_msg:
        flash("\n".join(flash_msg))
    return render_template("auth/login.html", latest_tag=os.getenv("LATEST_TAG"))


login_user_schema = LoginUserSchema()
register_user_schema = RegisterUserSchema()


@auth_blueprint.route("/login", methods=["POST"])
@redirect_if_logged_in
def login():
    current_app.logger.info("Login method")
    errs = login_user_schema.validate(request.form)

    if errs:
        return render_template(
            "auth/login.html",
            logged_in=False,
            errors=flatten_validation_errors(errs),
            login=request.form.get("login") if "login" not in errs else "",
        )

    login_fields: LoginUserSchema = login_user_schema.load(request.form)

    cred = Credentials.find_cred_on_login(login_fields["login"])

    if not cred:
        flash("Login not found, please register and try again")
        return render_template(
            "auth/login.html",
        )

    hashed_pass = hash_password(login_fields["password"], cred.salt)
    if hashed_pass != cred.hashed_pass:
        flash("Invalid password, please try again")
        return render_template("auth/login.html", login=login_fields["login"])

    user_id = cred.user_id

    accessToken: str = create_and_store_access_token_in_cache(user_id)

    res: Response = make_response(
        redirect(url_for("runs_blueprint.get_runs"), code=303)
    )
    res.set_cookie("accessToken", accessToken)

    return res


@auth_blueprint.route("/logout", methods=["POST"])
@auth_required
def logout():
    tok, user_id = get_token_and_user_id_from_cookies()
    current_app.logger.info(f"Logout called for user {user_id}")

    redis_cache.delete(tok)
    redis_cache.delete(f"user_id:{user_id}")

    flash("You have succesfully logged out 🎉", "message")

    res: Response = make_response(render_template("index.html"))
    res.set_cookie("accessToken", "", expires=0)
    return res


@auth_blueprint.route("/logout", methods=["GET"])
def logout_page():
    return redirect(url_for("auth_blueprint.render_login"))


@auth_blueprint.route("/password_recovery", methods=["POST"])
def password_recovery():
    login = request.form.get("login")

    current_app.logger.info(f"Password recovery called for {login}")

    cred = Credentials.find_cred_on_login(login)
    if cred and cred.user.email:
        current_app.logger.info(f"Sending recovery link to {cred.user.email}")
        PasswordRecoveryService.send_recovery_link(cred.user.email, login)
        return "ok"

    return "user email not found"


@auth_blueprint.route("/reset_password/<token>", methods=["GET"])
def reset_password(token: str):
    email = PasswordRecoveryService.verify_token(token)

    current_app.logger.info(f"Reset password called for {email}")

    if not email:
        return redirect(url_for("auth_blueprint.render_login"))

    login = Users.find_user_on_email(email).credentials.login

    return render_template("auth/reset_password.html", login=login, token=token)


@auth_blueprint.route("/reset_password", methods=["POST"])
def reset_password_post():
    login = request.form.get("login")
    token = request.form.get("token")

    if not PasswordRecoveryService.verify_token(token):
        # flash error message will come from verify_token call
        return redirect(url_for("auth_blueprint.render_login"))

    password = request.form.get("password")
    repeat_password = request.form.get("password_repeat")
    current_app.logger.info(f"Reset password called for {login}")

    # to reduce code dupe
    template_data = {
        "template_name_or_list": "auth/reset_password.html",
        "login": login,
        "token": token,
    }
    err: Optional[str] = None

    if password != repeat_password:
        err = "Passwords do not match, please try again"
    elif len(password) < MIN_PASS_LEN:
        err = f"Password must be at least {MIN_PASS_LEN} characters long, please try again"
    elif len(password) > MAX_PASS_LEN:
        err = (
            f"Password must be at most {MAX_PASS_LEN} characters long, please try again"
        )

    if err:
        flash(err, "error")
        return render_template(**template_data)

    try:
        Credentials.update_password(login, password)
    except ValueError:
        err = "New password cannot be the same as the old one, please try again"
    except Exception as e:
        current_app.logger.exception(
            f"Failed to reset password for {login} with error {str(e)}"
        )
        err = "An error occurred while resetting your password, please try again"

    if err:
        flash(err, "error")
        return render_template(**template_data)

    # add the token to redis so they cannot be used again
    redis_cache.setex(
        token, int(os.getenv("TOKEN_EXPIRATION_TIME_S")), "password_reset"
    )

    flash("Your password has been reset! Please login", "message")

    return redirect(url_for("auth_blueprint.render_login"))


# TODO - be logged out to register
@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("auth/register.html")

    errs = register_user_schema.validate(request.form)
    login = request.form.get("login")
    password = request.form.get("password")
    repeat_password = request.form.get("password_repeat")
    email = request.form.get("email")
    nick = request.form.get("nick")

    if errs:
        errors = flatten_validation_errors(errs)
        return render_template(
            "auth/register.html",
            errors=errors,
            login=login if "login" not in errors else "",
            nick=nick if "nick" not in errors else "",
            email=email if "email" not in errors else "",
            password=password if "password" not in errors else "",
            password_repeat=repeat_password if "password_repeat" not in errors else "",
        )

    if password != repeat_password:
        return render_template(
            "auth/register.html",
            errors={"password_repeat": "Passwords do not match, please try again"},
            login=login,
            nick=nick,
            email=email,
        )

    salt = create_salt()
    hashed_pass = hash_password(password, salt)

    with current_app.Session() as sess:
        try:
            creds = sess.query(Credentials).filter(Credentials.login == login).all()
            if creds:
                flash("Login already exists, please try again")
                return render_template("auth/register.html", nick=nick)

            user = Users(nick=nick, email=email, is_admin=0, is_readonly=0)


app/routes/nav_routes.py
import os

from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    send_from_directory,
    url_for,
)
from func_timeout import FunctionTimedOut, func_timeout
from sqlalchemy import text

from app.auth import admin_required, is_logged_in
from app.extensions import redis_cache

nav_blueprint = Blueprint("nav_blueprint", __name__)


@nav_blueprint.route("/favicon.ico")
def favicon():
    return send_from_directory(
        os.path.join(current_app.root_path, "static"),
        "favicon.ico",
        mimetype="image/vnd.microsoft.icon",
    )


@nav_blueprint.route("/")
def home():
    if is_logged_in():
        return redirect(url_for("runs_blueprint.get_runs"), code=303)

    return redirect(url_for("auth_blueprint.login"), code=303)


@nav_blueprint.route("/what-are-cooper-points")
def what_are_cooper_points():
    return render_template("what_are_cooper_points.html", logged_in=is_logged_in())


@nav_blueprint.route("/redis-health-check")
@admin_required
def redis_health_check():
    timeout: int = 5  # s
    try:
        ping = func_timeout(timeout, redis_cache.ping)
        return f"Redis ping returned with value: {str(ping)}", 200
    except FunctionTimedOut as fto:
        current_app.logger.error("Redis ping timed out " + str(fto))
        return f"Redis ping timed out after {timeout} seconds", 500
    except Exception as e:
        current_app.logger.error("Redis ping failed with " + str(e))
        return "Redis failed to ping", 500


@nav_blueprint.route("/rds-health-check")
@admin_required
def rds_health_check():
    try:
        with current_app.Session() as sess:
            res = sess.execute(text("SELECT 1"))
            if res.scalar() == 1:
                return "DB connection is healthy!", 200
            else:
                return "Query executed but incorrect result - should not happen", 500
    except Exception as e:
        current_app.logger.error("DB health check failed with " + str(e))
        return "DB connection failed with " + str(e), 500


@nav_blueprint.route("/log-check")
@admin_required
def log_check():
    current_app.logger.debug("this is a DEBUG message")
    current_app.logger.info("this is an INFO message")
    current_app.logger.warning("this is a WARNING message")
    current_app.logger.error("this is an ERROR message")
    current_app.logger.critical("this is a CRITICAL message")
    return "Logs written to logger", 200

app/templates/base.html
{% set logged_in = logged_in | default(False) %}
{% set errors = errors | default({}) %}

<!doctype html>
<html lang="">
<head>
    <title>Track My Run</title>
    <link rel="stylesheet" href="https://unpkg.com/missing.css@0.2.0/missing.min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="/static/js/htmx-1.9.12.min.js"></script>
    <script src="/static/js/jquery-3.7.1.slim.min.js"></script>
</head>
<body hx-boost="true">
    <main>
        <header>
            <h1>
                <a href="{{ url_for('nav_blueprint.home') }}" style="text-decoration: none">
                    Track My Run 🏃🏃🏽‍♀️
                </a>
            </h1>
            <h4>
                &#x21B3;
                    A web application to manage all of your aerobic activity <br>
                    &nbsp;&nbsp;&nbsp;, track your runs with GPS, and share them with friends.
            </h4>

            {% if not logged_in %}
                <div class="links-container">
                    <div class="left-links">
                        <a hx-get="{{ url_for('auth_blueprint.login') }}" hx-target="body" hx-push-url="true">Login</a>
                        |
                        <a hx-get="{{ url_for('auth_blueprint.register') }}" hx-target="body" hx-push-url="true">Register</a>
                    </div>
                    <div class="right-links">
                        <a hx-get="{{ url_for('nav_blueprint.what_are_cooper_points') }}" hx-target="body" hx-push-url="true">What are Cooper Points?</a>
                    </div>
                </div>
            {%else %}
                <div class="links-container">
                    <div class="left-links">
                        <button hx-get="{{ url_for('runs_blueprint.get_runs') }}" hx-target="body" hx-push-url="true">Show my activities</button>&nbsp;
                        <button hx-get="{{ url_for('runs_blueprint_refactored.new_run') }}" hx-target="body" hx-push-url="true">Input new activity</button>
                    </div>
                    <div class="right-links">
                        <a hx-get="{{ url_for('nav_blueprint.what_are_cooper_points') }}" hx-target="body" hx-push-url="true">What are Cooper Points?</a> |
                        <a hx-post="{{ url_for('auth_blueprint.logout') }}" hx-target="body" hx-push-url="true">Logout</a>
                    </div>
                </div>
            {%endif %}
        </header>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert-container">
                        <div class="alert alert-{{ category }}">
                            {{ message|safe }}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </main>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %} {% block content %} {% if logged_in %}
<div id="label-table-pagination-div">
  <div id="activity-count-div">
    Showing {{ runs_in_page}} of {{ total_count }} activities.
  </div>
  <table id="show-runs-table">
    <thead>
      <tr>
        <th></th>
        <th
          hx-get="/my_runs?order_by=date&order={{ order_vals['date'] }}"
          hx-target="body"
        >
          Date {% if order_vals["last_ordered"] == 'date' %} {% include
          'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=activity_start_time&order={{ order_vals['activity_start_time'] }}"
          hx-target="body"
        >
          Start Time {% if order_vals["last_ordered"] == 'activity_start_time'
          %} {% include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=distance_mi&order={{ order_vals['distance_mi'] }}"
          hx-target="body"
        >
          Dist (mi) {% if order_vals["last_ordered"] == 'distance_mi' %} {%
          include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=distance_yard&order={{ order_vals['distance_yard'] }}"
          hx-target="body"
        >
          Dist (yards) {% if order_vals["last_ordered"] == 'distance_yard' %} {%
          include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=duration_s&order={{ order_vals['duration_s'] }}"
          hx-target="body"
        >
          Duration (m:ss){% if order_vals["last_ordered"] == 'duration_s' %} {%
          include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=pace&order={{ order_vals['pace'] }}"
          hx-target="body"
        >
          Pace (min/mi){% if order_vals["last_ordered"] == 'pace' %} {% include
          'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=cooper_points&order={{ order_vals['cooper_points'] }}"
          hx-target="body"
        >
          Points{% if order_vals["last_ordered"] == 'cooper_points' %} {%
          include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th
          hx-get="/my_runs?order_by=activity_type&order={{ order_vals['activity_type'] }}"
          hx-target="body"
        >
          Activity{% if order_vals["last_ordered"] == 'activity_type' %} {%
          include 'fragments/show_chevron.html' %} {% endif %}
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody class="list">
      {% include 'runs/rows.html' %}
    </tbody>
  </table>
  {% include 'fragments/pagination.html' %}
</div>
{% endif %} {% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <form class="login-or-register" hx-post="/login" hx-push-url="true" id="login-form" hx-target="body">
        <label for="login">Login:</label>
        <input type="text" id="login" name="login">
        <span class="error">{{ errors.get('login', '') }}</span>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <span class="error">{{ errors.get('password', '') }}</span>
        <br>
        <input type="submit" value="Login" />
    </form>
    
{% endblock %}

app/templates/new_run.html
{% extends 'base.html' %}

{% block content %}
    <form id="new-run-form" hx-post="/create_run" hx-target="body">
        <h2>Input new run</h2>

        <div class="form-input-div">
            <div class="form-input-fields">
                <label for="date">Run date <i>(Defaults to today)</i></label>
                <input type="date" id="date" name="date" value="{{ current_date }}">
                <span class="error">{{ errors.get('date', '') }}</span>
            </div>
            
            <div class="form-input-fields">
                <label for="run_start_time">Start Time <i>(Optional)</i></label>
                <input type="time" id="run_start_time" name="run_start_time" step="60" min="00:00", max="24:00">
  
                <span class="error">{{ errors.get('run_start_time', '') }}</span>
            </div>
        </div>

        <div class="form-input-div">
            <div class="form-input-fields">
                <label for="distance_mi">Distance (mi)</label>
                <input type="number" id="distance_mi" name="distance_mi" step=".01" min="0.01" max="10" value="1">
                <span class="error">{{ errors.get('distance_mi', '') }}</span>
            </div>
            
            <div class="form-input-fields">
                <label for="run_time">Runtime Duration</label>
                <div style="display: flex;">
                    <input type="number" id="runtime_m" name="runtime_m" min="1" max="60" value="0"> m 
                    <span class="error">{{ errors.get('runtime_m', '') }}</span>
                    : 
                    <input type="number" id="runtime_s" name="runtime_s" min="0" max="59" value="0"> s 
                    <span class="error">{{ errors.get('runtime_s', '') }}</span>
                </div>
            </div>
        </div>

        <div id="enter-notes-area">
            <label for="notes">Optional Notes</label>
            <textarea id="notes-text-area" name="notes" placeholder="Enter a note about this run here..."></textarea>
            <span class="error">{{ errors.get('notes', '') }}</span>
        </div>

        <br>
        <input type="submit" value="Create run" />
    </form>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}

    <form class="login-or-register" hx-post="/register", hx-target="body">
        <h2>Register</h2>
        <label for="login">Login:</label>
        <input type="text" id="login" name="login">
        <span class="error">{{ errors.get('login', '') }}</span>

        <div id="password-inputs">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
            <span class="error">{{ errors.get('password', '') }}</span>

            <label for="password_repeat">Password (repeat):</label>
            <input type="password" id="password_repeat" name="password_repeat">
            <span class="error">{{ errors.get('password_repeat', '') }}</span>
        </div>

        <label for="nick">Want to enter an optional nick?</label>
        <input type="text" id="nick" name="nick">
        <span class="error">{{ errors.get('nick', '') }}</span>
        
        <br>
        <input type="submit" value="Register" />
    </form> 

{% endblock %}

app/templates/rows.html

{% for run in runs %}
    <tr class="run-row">
        <td></td>
        <td class="run-date-cell">{{ run.date }}</td>
        <td>{{ run.run_start_time_formatted if run.run_start_time_formatted else "" }}</td>
        <td class="dist-mi">{{ run.distance_mi }}</td>
        <td>{{ run.runtime_s // 60 }}:{{ "{:02d}".format(run.runtime_s % 60) }}</td>
        <td> {{ "{:.2f}".format((run.runtime_s/60) / run.distance_mi) }} </td>
        <td>
            <div data-overflow-menu>
                <div class="show-edit-links">
                    <button hx-get="{{ url_for('runs_blueprint.show_run', run_id= run.id) }}" hx-target="body" hx-push-url="true">Show</button>&nbsp;
                    <button hx-get="{{ url_for('runs_blueprint.edit_run_get', run_id= run.id) }}" hx-target="body" hx-push-url="true">Edit</button>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}

app/templates/what_are_cooper_points.html
{% extends 'base.html' %} {% block content %}
<link rel="stylesheet" href="/static/css/what-are-cooper-points.css" />
<div>
  <div class="p-with-image">
    <p>
      Cooper Points are a concept developed by
      <a
        href="https://www.cooperaerobics.com/About/Our-Leaders/Kenneth-H-Cooper,-MD,-MPH.aspx"
        target="_blank"
        >Dr. Kenneth H. Cooper</a
      >
      in 1968. They are a method to measure the intensity of an activity,
      assigning a number of points based on distance and time expended.
    </p>
    <img
      src="{{ url_for('static', filename='images/cooper.jpg') }}"
      alt="Dr. Kenneth H. Cooper"
    />
  </div>
  <p>
    The general goal is to track the number of points a person earns over a
    week, and the general recommendation by Dr. Cooper is to maintain a 30
    points / week value to maintain healthy aerobic levels.
  </p>
  <p>
    I built this application to help myself and others track these points with a
    simple and intuitive interface. Simply enter the distance and time you
    performed a walk, run, swim, or bike and it will calculate how many points
    you earned, saving it in the database.
  </p>
  <p>
    The full list of points can be found
    <a
      href="https://cooperaerobics.com/Downloads/About/Aerobics-Points-System.aspx"
      target="_blank"
      >here</a
    >.
  </p>
</div>

{% endblock %}